---
name: Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        #        os: [ubuntu-latest, macos-latest]
        os: [ubuntu-latest]
        python-version: ["3.10", "3.12"]
    steps:
      - name: Download code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run Simple tests
        run: |
          cd tests
          python unittests.py
